version: 0.3.2.{build}
image: Visual Studio 2019
build_script:
- ps: >-
    Remove-Item .\global.json

    $dotnet = Get-Command 'dotnet'

    & $dotnet --info

    & $dotnet restore /p:Version="$env:APPVEYOR_BUILD_VERSION"

    & $dotnet build /p:Version="$env:APPVEYOR_BUILD_VERSION"

    & $dotnet pack -o "$PWD\out\packages" /p:Version="$env:APPVEYOR_BUILD_VERSION"

    & $dotnet publish "$PWD\src\LanguageServer\LanguageServer.csproj" -f netcoreapp3.0 -o "$PWD\out\language-server" /p:Version="$env:APPVEYOR_BUILD_VERSION"

    & $dotnet publish "$PWD\src\LanguageServer.TaskReflection\LanguageServer.TaskReflection.csproj" -f netcoreapp3.0 -o "$PWD\out\task-reflection" /p:Version="$env:APPVEYOR_BUILD_VERSION"
test_script:
- ps: >-
    $dotnet = Get-Command 'dotnet'

    & $dotnet test "$PWD\test\LanguageServer.Engine.Tests\LanguageServer.Engine.Tests.csproj" /p:Version="$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: out\language-server
  name: MSBuildProjectTools.Server.$(APPVEYOR_BUILD_VERSION)
- path: out\task-reflection
  name: MSBuildProjectTools.Server.TaskReflection-$(APPVEYOR_BUILD_VERSION)
- path: out\packages\*.nupkg
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/tintoy
  api_key:
    secure: KmmArnxozcI5fVSCqThW1eLsI05fI0mjAIiSeFeH/6A=
  symbol_server: https://ci.appveyor.com/nuget/tintoy
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: 8dOYcBY+OqWsl9eM1N8zj2JWYQxIUw+2PdFGgp5sH6QRO69h/gG0lvGjSuYBGhwv
  artifact: /MSBuildProjectTools\..*\.zip/
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true  # only publish when tagged
notifications:
- provider: Email
  to:
  - tintoy@tintoy.io
  subject: 'Build failed: msbuild-project-tools-server'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
